"""empty message

Revision ID: 32be5ab35a93
Revises: 3f9cbc895811
Create Date: 2022-05-11 14:22:33.203393

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '32be5ab35a93'
down_revision = '3f9cbc895811'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('team', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'team')
    # ### end Alembic commands ###
