"""empty message

Revision ID: 3f9cbc895811
Revises: f520fe018cec
Create Date: 2022-05-11 09:50:29.435900

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3f9cbc895811'
down_revision = 'f520fe018cec'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('win_loss', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'win_loss')
    # ### end Alembic commands ###
