"""empty message

Revision ID: 880a9131046f
Revises: 33dba63fa714
Create Date: 2022-05-09 11:31:34.965707

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '880a9131046f'
down_revision = '33dba63fa714'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('icon', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'icon')
    # ### end Alembic commands ###
