"""empty message

Revision ID: db43f56b81b0
Revises: 
Create Date: 2022-05-10 16:42:51.111572

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'db43f56b81b0'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pokemon',
    sa.Column('pokemon_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('bexp', sa.String(), nullable=True),
    sa.Column('shiny', sa.String(), nullable=True),
    sa.Column('ability', sa.String(), nullable=True),
    sa.Column('hp', sa.String(), nullable=True),
    sa.Column('atk', sa.String(), nullable=True),
    sa.Column('defense', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('pokemon_id')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('first_name', sa.String(), nullable=True),
    sa.Column('last_name', sa.String(), nullable=True),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('username', sa.String(), nullable=True),
    sa.Column('password', sa.String(), nullable=True),
    sa.Column('trainer_since', sa.DateTime(), nullable=True),
    sa.Column('icon', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_username'), 'user', ['username'], unique=True)
    op.create_table('poke_team',
    sa.Column('poketeam_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('poketeam_id')
    )
    op.create_table('pokedex',
    sa.Column('pokedex_id', sa.Integer(), nullable=False),
    sa.Column('poketeam_id', sa.Integer(), nullable=True),
    sa.Column('pokemon_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['pokemon_id'], ['pokemon.pokemon_id'], ),
    sa.ForeignKeyConstraint(['poketeam_id'], ['poke_team.poketeam_id'], ),
    sa.PrimaryKeyConstraint('pokedex_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('pokedex')
    op.drop_table('poke_team')
    op.drop_index(op.f('ix_user_username'), table_name='user')
    op.drop_table('user')
    op.drop_table('pokemon')
    # ### end Alembic commands ###
